const cardsData = [
  {
    id: 1,
    titulo: "Congresso Nacional",
    descricao: "O Congresso Nacional é um símbolo político do Brasil, composto por duas torres e cúpulas que abrigam a Câmara dos Deputados e o Senado Federal, em Brasília, capital do país.",
    imagens: ["images/congresso1.jpg", "images/congresso2.jpg", "images/congresso3.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Instituições Governamentais"
  },
  {
    id: 2,
    titulo: "Palácio Do Itamaraty",
    descricao: "O Palácio do Itamaraty abriga o Ministério das Relações Exteriores, destaca-se por sua arquitetura imponente, espelhos d'água e acervo artístico, sendo símbolo da diplomacia brasileira.",
    imagens: ["images/palacio1.jpg", "images/palacio2.jpg", "images/palacio3.jpeg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Instituições Governamentais"
  },
  {
    id: 3,
    titulo: "Memorial JK",
    descricao: "O Memorial JK homenageia o ex-presidente Juscelino Kubitschek, abriga seu mausoléu, objetos pessoais e exposições sobre sua vida e legado, sendo marco histórico de Brasília.",
    imagens: ["images/memorial1.webp", "images/memorial2.jpg", "images/memorial3.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Museus"
  },
  {
    id: 4,
    titulo: "Torre De TV",
    descricao: "A Torre de TV de Brasília oferece vista panorâmica da cidade, possui mirante, feiras e eventos culturais, sendo ponto turístico marcante e local de convivência popular.",
    imagens: ["images/torretv1.jpg", "images/torretv2.jpeg", "images/torretv3.jpeg", "images/torretv4.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Paisagens"
  },
  {
    id: 5,
    titulo: "Santuário Dom Bosco",
    descricao: "O Santuário Dom Bosco é conhecido por seus vitrais azuis que criam um ambiente místico, homenageando o padroeiro de Brasília e oferecendo um espaço de fé e contemplação.",
    imagens: ["images/santuario1.jpg", "images/santuario3.jpg", "images/santuario2.jpg", "images/santuario4.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Santuários"
  },
  {
    id: 6,
    titulo: "Pontão",
    descricao: "O Pontão do Lago Sul é um centro de lazer em Brasília, situado às margens do Lago Paranoá. Oferece restaurantes, bares, lojas e atividades ao ar livre, como caminhadas e esportes náuticos. É conhecido por suas áreas verdes e vistas panorâmicas, especialmente durante o pôr do sol.",
    imagens: ["images/potao1.jpg", "images/pontao2.jpg", "images/pontao3.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Paisagens"
  },
  {
    id: 7,
    titulo: "Mané Garrincha",
    descricao: "O Estádio Mané Garrincha é uma das maiores arenas do Brasil, recebe jogos, shows e eventos, com arquitetura moderna e destaque na paisagem de Brasília.",
    imagens: ["images/mane1.jpg", "images/mane2.jpg", "images/mane3.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Esportes"
  },
  {
    id: 8,
    titulo: "Catedral Metropolitana",
    descricao: "A Catedral Metropolitana de Brasília, projetada por Oscar Niemeyer, destaca-se por sua arquitetura moderna em forma de coroa e vitrais coloridos, simbolizando fé e luz na capital.",
    imagens: ["images/catedral3.jpg", "images/catedral2.jpg", "images/catedral1.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Santuários"
  },
  {
    id: 9,
    titulo: "Museu dos Indígenas",
    descricao: "O Memorial dos Povos Indígenas, projetado por Oscar Niemeyer, possui arquitetura inspirada em uma maloca circular, tradicional habitação indígena. Localizado em Brasília, abriga e preserva a cultura e história dos povos indígenas brasileiros, com acervo de mais de 2 mil artefatos.",
    imagens: ["images/ingio1.jpg", "images/indio2.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Museus"
  },
  {
    id: 10,
    titulo: "Supremo Tribunal Federal",
    descricao: "O Supremo Tribunal Federal é a mais alta instância da Justiça no Brasil. Localizado na Praça dos Três Poderes, em Brasília, destaca-se pela arquitetura moderna e pela escultura “A Justiça” na entrada. É responsável por garantir o cumprimento da Constituição e oferece visitas públicas guiadas.",
    imagens: ["images/stf1.jpg", "images/stf2.jpg", "images/stf3.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Instituições Governamentais"
  },
  {
    id: 11,
    titulo: "Ponte JK",
    descricao: "A Ponte JK cruza o Lago Paranoá e liga o Plano Piloto ao Lago Sul. É famosa por seu design arrojado com arcos inclinados, sendo um dos cartões-postais de Brasília.",
    imagens: ["images/jk1.jpg", "images/jk2.jpg", "images/jk3.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "Todos os Dias",
    turismo: "Monumentos"
  },
  {
    id: 12,
    titulo: "Torre Digital",
    descricao: "A Torre Digital, conhecida como Flor do Cerrado, transmite sinais de rádio e TV em Brasília. Com design futurista e 170 metros de altura, oferece mirante com vista panorâmica da cidade.",
    imagens: ["images/digital1.jpg", "images/digital2.jpg", "images/digitl3.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Monumentos", 
  },
  {
    id: 13,
    titulo: "Museu Oscar Niemeyer",
    descricao: "O Museu Oscar Niemeyer, localizado em Curitiba, destaca-se pela arquitetura inovadora, com o icônico anexo em forma de olho. Dedicado à arte, arquitetura e design, abriga exposições permanentes e temporárias.",
    imagens: ["images/museuoscar1.avif", "images/museuoscar2.avif"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Museus"
  },
  {
    id: 14,
    titulo: "Casa Do Presidente",
    descricao: "O Palácio da Alvorada é a residência oficial do Presidente do Brasil. Projetado por Oscar Niemeyer, é símbolo da arquitetura modernista e um dos principais marcos de Brasília.",
    imagens: ["images/casapresidente1.jpg", "images/casapresidente2.webp", "images/casapresidente3.jpg", "images/casapresidente3.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Instituições Governamentais"
  },
  {
    id: 15,
    titulo: "Palácio Do Jaburu",
    descricao: "O Palácio do Jaburu é a residência oficial do Vice-Presidente do Brasil. Projetado por Oscar Niemeyer, está situado entre os Palácios do Planalto e da Alvorada, com jardins assinados por Burle Marx.",
    imagens: ["images/jaburu1.jpg", "images/jaburu2.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Instituições Governamentais"
  },
  {
    id: 16,
    titulo: "Museu Nacional",
    descricao: "O Museu Nacional da República, em Brasília, destaca-se por sua cúpula branca e arquitetura moderna. Inaugurado em 2006, abriga exposições de arte contemporânea e eventos culturais.",
    imagens: ["images/museunacional1.avif", "images/museunacional3.jpg", "images/museunacional3.webp"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Museus"
  },
  {
    id: 17,
    titulo: "Teatro Nacional Cláudio Santoro",
    descricao: "O Teatro Nacional Cláudio Santoro é um dos principais espaços culturais de Brasília. Possui arquitetura arrojada e recebe diversas apresentações artísticas e eventos culturais.",
    imagens: ["images/teatro1.jpeg", "images/teatro2.avif", "images/teatro3.avif"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis",
    funcionamento: "semana",
    turismo: "Cultura"
  },
  {
    id: 18,
    titulo: "Conjunto Nacional",
    descricao: "Inaugurado em 1971, o Shopping Conjunto Nacional é o primeiro centro comercial de Brasília e o segundo do Brasil. Possui mais de 320 lojas e é o maior shopping do Distrito Federal.",
    imagens: ["images/Conjunto1.jpg", "images/conjunto2.jpg"],
    horario: "07:00h - 18:00h",
    categoria: "turismo",
    entrada: "Grátis", 
    funcionamento: "Todos os Dias",
    turismo: "Comércio"
  }
];
